param(
    [string]$CudaRoot = ""
)

# Compiles crates/matanyone-core/kernels/matanyone_kernels.cu into the embedded fatbin header.
# The fatbin carries sm_86 SASS (RTX 30/40) plus compute_86 PTX for newer GPUs to JIT.

$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path | Split-Path -Parent
if (-not $CudaRoot) {
    $CudaRoot = if ($env:CUDA_ROOT) { $env:CUDA_ROOT } else { "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v13.1" }
}

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
$vs = & $vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
$msvc = Get-ChildItem "$vs\VC\Tools\MSVC" | Sort-Object Name | Select-Object -Last 1
$ccbin = Join-Path $msvc.FullName "bin\Hostx64\x64"

$KernelDir = Join-Path $Root "crates\matanyone-core\kernels"
$Source = Join-Path $KernelDir "matanyone_kernels.cu"
$Fatbin = Join-Path $env:TEMP "matanyone_kernels.fatbin"
& (Join-Path $CudaRoot "bin\nvcc.exe") --fatbin -O3 -ccbin $ccbin `
    -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=compute_86 `
    -o $Fatbin $Source
if ($LASTEXITCODE -ne 0) { throw "nvcc failed" }

$bytes = [System.IO.File]::ReadAllBytes($Fatbin)
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("// Auto-generated by scripts/build_kernels.ps1 from matanyone_kernels.cu. Do not edit.")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <cstdint>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const uint8_t g_cubin_data[] = {")
for ($i = 0; $i -lt $bytes.Length; $i += 12) {
    $end = [Math]::Min($i + 12, $bytes.Length)
    $line = ($bytes[$i..($end - 1)] | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    [void]$sb.AppendLine("    $line,")
}
[void]$sb.AppendLine("};")
[System.IO.File]::WriteAllText((Join-Path $KernelDir "matanyone_cubin.h"), $sb.ToString().Replace("`r`n", "`n"))
Remove-Item $Fatbin
Write-Host "Wrote matanyone_cubin.h ($($bytes.Length) bytes)"
