import argparse
import urllib.request
from pathlib import Path

import torch

from matanyone2.utils.get_default_model import get_matanyone2_model


CHECKPOINT_URL = "https://github.com/pq-yang/MatAnyone2/releases/download/v1.0.0/matanyone2.pth"


class EncoderWithNormalize(torch.nn.Module):
    def __init__(self, model):
        super().__init__()
        self.pixel_mean = model.pixel_mean
        self.pixel_std = model.pixel_std
        self.pixel_encoder = model.pixel_encoder

    def forward(self, image):
        image = (image - self.pixel_mean) / self.pixel_std
        return self.pixel_encoder(image)


def download_checkpoint(path: Path) -> None:
    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    print(f"Downloading checkpoint to {path}")
    urllib.request.urlretrieve(CHECKPOINT_URL, path)


def tensor_line(name: str, tensor: torch.Tensor) -> str:
    return f"- `{name}`: shape `{tuple(tensor.shape)}`, dtype `{tensor.dtype}`, device `{tensor.device}`"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ckpt", default="models/matanyone2.pth")
    parser.add_argument("--onnx", default="models/encoder.onnx")
    parser.add_argument("--shapes", default="docs/tensor_shapes.md")
    parser.add_argument("--opset", type=int, default=17)
    parser.add_argument("--height", type=int, default=720)
    parser.add_argument("--width", type=int, default=1280)
    args = parser.parse_args()

    if not torch.cuda.is_available():
        raise RuntimeError("CUDA PyTorch is required for this export.")

    ckpt_path = Path(args.ckpt)
    onnx_path = Path(args.onnx)
    shapes_path = Path(args.shapes)
    download_checkpoint(ckpt_path)

    device = torch.device("cuda")
    model = get_matanyone2_model(str(ckpt_path), device=device).eval()
    encoder = EncoderWithNormalize(model).to(device).eval()

    sample = torch.randn(1, 3, args.height, args.width, device=device)

    with torch.inference_mode():
        outputs = encoder(sample)

    names = ["f16", "f8", "f4", "f2", "f1"]
    lines = [
        "# Tensor Shapes",
        "",
        "Generated by `scripts/export_encoder.py`.",
        "",
        tensor_line("input", sample),
        *[tensor_line(name, tensor) for name, tensor in zip(names, outputs)],
        "",
    ]
    shapes_path.parent.mkdir(parents=True, exist_ok=True)
    shapes_path.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))

    onnx_path.parent.mkdir(parents=True, exist_ok=True)
    torch.onnx.export(
        encoder,
        sample,
        onnx_path,
        input_names=["image"],
        output_names=names,
        dynamic_axes={
            "image": {0: "batch", 2: "height", 3: "width"},
            "f16": {0: "batch", 2: "height16", 3: "width16"},
            "f8": {0: "batch", 2: "height8", 3: "width8"},
            "f4": {0: "batch", 2: "height4", 3: "width4"},
            "f2": {0: "batch", 2: "height2", 3: "width2"},
            "f1": {0: "batch", 2: "height", 3: "width"},
        },
        opset_version=args.opset,
        do_constant_folding=True,
        dynamo=False,
    )
    print(f"Wrote {onnx_path}")


if __name__ == "__main__":
    main()
